#!/usr/bin/env bash
# Pins the CM108 PTT udev rule format generated by
# installer/linux/lib/udev-rule.sh — the exact bytes the PTT wizard
# installs (via sudo) at /etc/udev/rules.d/99-svxlink-ptt.rules.
#
# The rule is the ONLY thing standing between the container and a
# root:root 0600 hidraw node (GroupAdd=keep-groups has no group to carry
# for hidraw), so every field is load-bearing:
#   * SUBSYSTEM/idVendor/idProduct select the detected device (product id
#     substituted — 0d8c makes plain audio dongles too, so vendor-only
#     matching would symlink the wrong node),
#   * GROUP="audio" + MODE="0660" grant the access keep-groups rides on,
#   * SYMLINK+="svxlink-ptt" is the stable name the quadlet's AddDevice=
#     points at (raw /dev/hidrawN renumbers across replugs),
#   * KERNELS=="<usb port>" appears ONLY when a second argument is given
#     (the wizard passes it only with >1 identical adapter present —
#     an unconditional KERNELS pin would break PTT on every port change).
#
# The test sources the SAME lib svx.tmpl sources from the staged payload,
# so production rule text and test can't drift. Run from the repo root.

set -euo pipefail

UDEV_LIB=${UDEV_LIB:-installer/linux/lib/udev-rule.sh}
if [[ ! -f "$UDEV_LIB" ]]; then
    echo "[ERR] $UDEV_LIB not found (run from repo root)" >&2
    exit 2
fi
# shellcheck source=/dev/null
. "$UDEV_LIB"

fail=0
ok()   { echo "  [OK]   $1"; }
miss() { echo "  [MISS] $1"; fail=1; }

# --- single-device rule (no KERNELS pin) ---------------------------------
one=$(udev_rule_cm108 013c)

if [[ "$(wc -l <<<"$one")" == 1 ]]; then
    ok "single-device rule is exactly one line"
else
    miss "single-device rule is not exactly one line"
fi
for field in \
    'SUBSYSTEM=="hidraw"' \
    'ATTRS{idVendor}=="0d8c"' \
    'ATTRS{idProduct}=="013c"' \
    'GROUP="audio"' \
    'MODE="0660"' \
    'SYMLINK+="svxlink-ptt"'
do
    if grep -qF "$field" <<<"$one"; then
        ok "field present: $field"
    else
        miss "field missing: $field"
    fi
done
if grep -qF 'KERNELS' <<<"$one"; then
    miss "KERNELS pin present without a second argument (would break on port change)"
else
    ok "no KERNELS pin in the single-device rule"
fi

# --- two-device case: the wizard pins the chosen adapter's USB port ------
two=$(udev_rule_cm108 013a "3-1.4")

if grep -qF 'ATTRS{idProduct}=="013a"' <<<"$two"; then
    ok "product id substituted in the pinned rule"
else
    miss "product id not substituted in the pinned rule"
fi
if grep -qF 'KERNELS=="3-1.4"' <<<"$two"; then
    ok "KERNELS pin present with a second argument"
else
    miss "KERNELS pin missing despite a second argument"
fi
# Pinned ordering: KERNELS is a match key and must sit with the other
# match keys, before the GROUP assignment.
if grep -qF 'KERNELS=="3-1.4", GROUP="audio"' <<<"$two"; then
    ok "KERNELS inserted before GROUP (match keys before assignments)"
else
    miss "KERNELS not inserted directly before GROUP"
fi
# The pinned rule must still carry every unconditional field.
for field in 'GROUP="audio"' 'MODE="0660"' 'SYMLINK+="svxlink-ptt"'; do
    if grep -qF "$field" <<<"$two"; then
        ok "pinned rule keeps: $field"
    else
        miss "pinned rule lost: $field"
    fi
done

if (( fail )); then
    echo
    echo "[ERR] udev rule format broken — see entries above." >&2
    exit 1
fi
echo "[OK] CM108 udev rule format is correct (with and without KERNELS pin)."
